---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
Calendar:
  extensions:
    - CalendarExtension
CalendarEvent:
  extensions:
    - CalendarEventExtension
SilverStripe\Assets\Flysystem\AssetAdapter:
  file_permissions:
    'file':
      'public': '0644'
      'private': '0600'
SilverStripe\Assets\InterventionBackend:
  flush_enabled: false
